version: "3.7"
services:
  db:
    image: mysql:5
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: copyto.me
    volumes:
      - copyto.me_db:/var/lib/mysql
volumes:
    copyto.me_db:
