version: "3.7"
services:
  copyto:      
    build:
      context: ./
      dockerfile: ./service/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - AUTHENTICATION__GOOGLE__CLIENTID
      - AUTHENTICATION__GOOGLE__CLIENTSECRET
      - SENDGRIDUSER
      - SENDGRIDKEY
    volumes:
      - ./service:/source/service
      - ./ui:/source/ui
      - ./npm:/source/npm
  db:
    image: mysql:5
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: copyto.me
    volumes:
      - copyto.me_db:/var/lib/mysql
volumes:
    copyto.me_db:
