version: "3.7"
services:
  ui:      
    image: node:10
    working_dir: /source/ui
    command: npm run start -- --host 0.0.0.0
    depends_on:
      - service
      - db
    ports:
      - '4200:4200'
    volumes:
      - ./ui:/source/ui
      - ./npm:/source/npm
  service:      
    build:
      context: ./
      dockerfile: ./service/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - AUTHENTICATION__GOOGLE__CLIENTID
      - AUTHENTICATION__GOOGLE__CLIENTSECRET
      - SENDGRIDUSER
      - SENDGRIDKEY
    volumes:
      - ./service:/source/service
      - ./ui:/source/ui
      - ./npm:/source/npm
  db:
    image: mysql:5
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: copyto.me
    volumes:
      - copyto.me_db:/var/lib/mysql
volumes:
    copyto.me_db:
